services:

  ipfs:
    image: ipfs/go-ipfs:latest
    container_name: ipfs
    volumes:
      - ./data:/data/ipfs
      - ./export:/export
    ports:
      - "4001:4001"
      - "4001:4001/udp"
      - "5001:5001"
      - "8080:8080"
    restart: unless-stopped